# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish app

on:
  push:

env:
  node-version: 12.16.3
  releaseType: draft

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - name: set CI version
      run: |
        jq --arg runnumber "$GITHUB_RUN_NUMBER" '.version += "ci."+$runnumber' package.json > package.json
      shell: bash
    - name: Cat for GitHub Actions
      uses: pCYSl5EDgo/cat@1.0.0
      id: package
      with:
        path: package.json
    - run: echo $TEXT
      env:
        TEXT: ${{ steps.package.outputs.text }}
    - name: change release type to ${{ env.releaseType }}
      run: |
        sed -e 's/\(releaseType: \).*/\1'\''${{ env.releaseType }}'\'',/' vue.config.js > vue.config.js
      shell: bash
    - name: Cat for GitHub Actions
      uses: pCYSl5EDgo/cat@1.0.0
      id: vue
      with:
        path: vue.config.js
    - run: echo $TEXT
      env:
        TEXT: ${{ steps.vue.outputs.text }}
    - name: Get cache directory path
      id: cache-dir-path
      run: |
        echo "::set-output name=yarn-dir::$(yarn cache dir)"
        echo "::set-output name=electron-dir::$home\.cache"
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          ${{ steps.cache-dir-path.outputs.yarn-dir }}
          ${{ steps.cache-dir-path.outputs.electron-dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name : Build and Release
      run: yarn electron:publish